// <auto-generated />
using System;
using BetManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BetManagement.Migrations
{
    [DbContext(typeof(BetDbContext))]
    [Migration("20210407220028_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BetManagement.Models.Match", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("MatchDate");

                    b.Property<DateTime>("MatchTime");

                    b.Property<string>("Sport");

                    b.Property<string>("TeamA");

                    b.Property<string>("TeamB");

                    b.HasKey("ID");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("BetManagement.Models.MatchOdds", b =>
                {
                    b.Property<int>("ID");

                    b.Property<int>("MatchId");

                    b.Property<decimal>("Odd");

                    b.Property<string>("Specifier");

                    b.HasKey("ID", "MatchId");

                    b.ToTable("MatchOdds");
                });
#pragma warning restore 612, 618
        }
    }
}
